[package]
name = "libzodream"
version = "0.1.0"
edition = "2021"

[lib]
crate-type=["lib", "cdylib"]

[dependencies]
lz4 = "1.26.0"
skipjack = "0.2.0"
image = "0.25.2"
video-rs = "0.9.0"
safer-ffi.version = "0.1.12"
safer-ffi.features = [
    "async-fn",
    "futures",
]

[features]
headers = ["safer-ffi/headers"]